# Generated by Django 4.2.8 on 2024-09-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0007_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='nophoto.jpg', null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
