# Generated by Django 4.2.8 on 2024-09-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0010_post_text2_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(default='nophoto.jpg', upload_to='authors/'),
        ),
    ]
